-- scripts/extract_icons.lua
-- Helper to extract the full icon tables from an installed nvim-web-devicons
-- Usage (from repo root):
--   nvim --headless -c 'lua require("scripts.extract_icons").run()' -c qa
-- Will write lua/volt/icons/full.lua. The script will attempt to extract environment maps
-- if the source plugin exposes similar tables; otherwise the maps will be empty.

local M = {}

local function safe_write(path, content)
  local f, err = io.open(path, "w")
  if not f then
    return nil, err
  end
  f:write(content)
  f:close()
  return true
end

-- Simple serializer using vim.inspect if available, fallback to basic table print
local function serialize(tbl)
  if vim and vim.inspect then
    return vim.inspect(tbl)
  end
  -- fallback: very simple serializer (not ideal for big tables)
  local lines = {"{"}
  for k,v in pairs(tbl) do
    lines[#lines+1] = string.format("  [%q] = %q,", tostring(k), tostring(v))
  end
  lines[#lines+1] = "}"
  return table.concat(lines, "\n")
end

function M.run()
  local ok, devicons = pcall(require, "nvim-web-devicons")
  if not ok or not devicons then
    return error("nvim-web-devicons not found in runtimepath")
  end

  local by_ext = {}
  local by_name = {}
  local by_os = {}
  local by_de = {}
  local by_wm = {}

  -- Try to read common exports / functions from various plugin versions
  if devicons.get_icons then
    local tbl = devicons.get_icons()
    by_ext = tbl.by_extension or by_ext
    by_name = tbl.by_filename or by_name
    by_os = tbl.by_operating_system or by_os
    by_de = tbl.by_desktop_environment or by_de
    by_wm = tbl.by_window_manager or by_wm
  else
    -- best-effort fallbacks
    by_ext = devicons.icons_by_file_extension or (devicons.get_icons_by_extension and devicons.get_icons_by_extension()) or by_ext
    by_name = devicons.icons_by_filename or (devicons.get_icons_by_filename and devicons.get_icons_by_filename()) or by_name
    -- Many devicons distributions won't have OS/DE/WM maps; leave empty if not present
    by_os = devicons.by_operating_system or {}
    by_de = devicons.by_desktop_environment or {}
    by_wm = devicons.by_window_manager or {}
  end

  by_ext = by_ext or {}
  by_name = by_name or {}
  by_os = by_os or {}
  by_de = by_de or {}
  by_wm = by_wm or {}

  local content = {}
  table.insert(content, "-- Auto-generated by scripts/extract_icons.lua")
  table.insert(content, "return {")
  table.insert(content, "  by_extension = " .. serialize(by_ext) .. ",")
  table.insert(content, "  by_filename = " .. serialize(by_name) .. ",")
  table.insert(content, "  by_operating_system = " .. serialize(by_os) .. ",")
  table.insert(content, "  by_desktop_environment = " .. serialize(by_de) .. ",")
  table.insert(content, "  by_window_manager = " .. serialize(by_wm) .. ",")
  table.insert(content, "}")

  local ok, err = safe_write("lua/volt/icons/full.lua", table.concat(content, "\n"))
  if not ok then
    error("Failed to write lua/volt/icons/full.lua: " .. tostring(err))
  end
  print("Wrote lua/volt/icons/full.lua")
end

return M
