-- lua/volt/icons/full.lua
-- Extracted subset of the full nvim-web-devicons dataset including environment maps.
-- This file is intentionally a small curated subset for demonstration.
-- Use scripts/extract_icons.lua to regenerate a full table from nvim-web-devicons.

return {
  by_extension = {
    lua = { icon = "", color = "#51A0CF", name = "Lua" },
    js  = { icon = "", color = "#EAD41C", name = "JavaScript" },
    ts  = { icon = "", color = "#2b7489", name = "TypeScript" },
    py  = { icon = "", color = "#3572A5", name = "Python" },
    rs  = { icon = "", color = "#dea584", name = "Rust" },
    go  = { icon = "", color = "#00ADD8", name = "Go" },
    md  = { icon = "", color = "#083fa1", name = "Markdown" },
    json= { icon = "ﬥ", color = "#cbcb41", name = "JSON" },
    sh  = { icon = "", color = "#6e4a7e", name = "Shell" },
    toml= { icon = "", color = "#9c4221", name = "TOML" },
    -- more entries can be autogenerated by the extraction script
  },
  by_filename = {
    [".gitignore"] = { icon = "", color = "#F54D27", name = "GitIgnore" },
    ["makefile"]   = { icon = "", color = "#6D8086", name = "Makefile" },
    ["dockerfile"] = { icon = "", color = "#0db7ed", name = "Dockerfile" },
    ["readme.md"]  = { icon = "", color = "#083fa1", name = "Readme" },
    ["license"]    = { icon = "", color = "#6d8086", name = "License" },
    ["package.json"]= { icon = "", color = "#cbcb41", name = "Npm" },
    ["tsconfig.json"]= { icon = "", color = "#2b7489", name = "TSConfig" },
    ["cargo.toml"] = { icon = "", color = "#dea584", name = "Cargo" },
    [".env"]       = { icon = "", color = "#4f5d95", name = "Env" },
    ["init.lua"]   = { icon = "", color = "#51A0CF", name = "LuaInit" },
    -- more entries...
  },

  -- Environment-specific maps (small curated examples)
  by_operating_system = {
    linux = { icon = "", color = "#83a598", name = "Linux" },
    macos = { icon = "", color = "#000000", name = "macOS" },
    windows = { icon = "", color = "#00a4ef", name = "Windows" },
  },

  by_desktop_environment = {
    gnome = { icon = "﫧", color = "#2E8B57", name = "GNOME" },
    kde   = { icon = "", color = "#5C2D91", name = "KDE" },
    xfce  = { icon = "", color = "#2A9D8F", name = "XFCE" },
  },

  by_window_manager = {
    i3      = { icon = "󰙯", color = "#61AFEF", name = "i3" },
    sway    = { icon = "󰙯", color = "#61AFEF", name = "Sway" },
    openbox = { icon = "󰙠", color = "#6D8086", name = "OpenBox" },
  },
}
